version: "3.9"

services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    container_name: app
    volumes:
      - ../:/workspace
    ports:
      - "8080:8080" # Quarkusのデフォルトポート
    stdin_open: true
    tty: true
    restart: alaways